name: CMake

on:
  push:
    branches:
      - main
      - ci
  pull_request:
    branches:
      - main

jobs:
  msvc:
    strategy:
      matrix:
        include:
          - name: VS2019-x86
            vmimage: windows-2019
            cmakeplatform: Win32
          - name: VS2019-x64
            vmimage: windows-2019
            cmakeplatform: x64
          - name: Mingw-w64-x64
            vmimage: ubuntu-20.04
            cmakeplatform: x64

    runs-on: ${{ matrix.vmimage }}
    name: ${{ matrix.name }}
    steps:
    - uses: actions/checkout@v3

    - name: Generate CMake Projects
      working-directory: ${{runner.workspace}}
      shell: cmd
      run: |
        cmake -S Tolk -B build -A ${{ matrix.cmakeplatform }} -DCMAKE_INSTALL_PREFIX=install -DCMAKE_TOOLCHAIN_FILE=../tolk/CMake/mingwcc64.toolchain.cmake

    - name: Build CMake Projects
      working-directory: ${{runner.workspace}}
      shell: cmd
      run: |
        cmake --build build

    - name: Install CMake Projects
      working-directory: ${{runner.workspace}}
      shell: cmd
      run: |
        cmake --build build --target install

    - uses: actions/upload-artifact@v3
      with:
        name: tolk-${{ matrix.name }}
        path: ${{runner.workspace}}/install
